# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v2.0.1
_src_path: https://github.com/napari/napari-plugin-template
display_name: Flopa
email: cockovaz@natur.cuni.cz
full_name: Zuzana Cockova
github_repository_url: provide later
github_username_or_organization: cockovaz
include_reader_plugin: false
include_sample_data_plugin: false
include_widget_plugin: true
include_writer_plugin: false
install_dependabot: false
install_precommit: true
license: MIT
module_name: napari_flopa
plugin_name: napari-flopa
short_description: Flim (fluorescence lifetime) image data opening, processing and
    analysis
